# Generated by Django 3.2 on 2023-05-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodstuffs_assistant', '0002_auto_20230503_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('id',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id',), 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
