# Generated by Django 3.2 on 2023-05-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230504_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, help_text='Загрузите картинку', null=True, upload_to='recipes/images/', verbose_name='Фотография блюда'),
        ),
    ]
